<?php
/**
 * Created by PhpStorm.
 * User: zhengjq
 * Date: 2017/8/8
 * Time: 15:18
 */

namespace app\commands\controllers;


use app\commands\crawlers\common\Filter;
use app\common\util\Snoopy;
use yii\console\Controller;

class CrawlerController extends Controller
{
    public $snoopy;
    public $crawlConfig;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        set_time_limit(0);
        $this->snoopy = new Snoopy();
        $this->snoopy->agent = "Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)";
        $this->snoopy->rawheaders["Pragma"] = "no-cache";
    }

    /**
     * 增量抓取
     */
    public function actionRun()
    {
        $this->actionList();
        $this->actionDetail();
    }

    /**
     * 整站抓取
     */
    public function actionRunAll()
    {
        $this->actionIndex();
        $this->actionList();
        $this->actionDetail();
    }

    public function actionIndex()
    {
    }

    public function actionList()
    {
    }

    public function actionDetail()
    {
    }

    /**
     * 提取链接
     * @param $html
     * @param string $configName
     * @return array
     */
    protected function getNextCrawlInfo($html, $configName = '')
    {
        require_once('./common/util/phpQuery/phpQuery.php');

        $config = $this->crawlConfig[$configName];
        $dom = \phpQuery::newDocumentHTML($html);

        $result = [];

        foreach ($config as $key => $rule){
            $query = isset($rule['root']) ? $dom[$rule['root']] : $dom;

            if ($key == 'url'){
                $result[$key] = [];
                foreach ($query as $item){
                    if (isset($rule['strip'])){
                        if ($this->excuteQuery(pq($item), $rule['strip'])) continue;
                    }

                    $url = $this->excuteQuery(pq($item), $rule['rule']);

                    if (isset($rule['filter']) && strpos($url, $rule['filter'])) continue;
                    if (isset($rule['contains']) && strpos($url, $rule['contains']) === false) continue;
                    array_push($result[$key], $url);
                }
            }else{
                $result[$key] = $this->excuteQuery(pq($query), $rule['rule']);
            }
        }
        $dom->unloadDocument();
        return $result;
    }

    protected function getArticleInfo($html,$configName = 'detailPage')
    {
        require_once('./common/util/phpQuery/phpQuery.php');

        $config = $this->crawlConfig[$configName];
        $query = \phpQuery::newDocumentHTML($html);

        $result = [];
        foreach ($config as $key => $rule){
            $result[$key] = $this->excuteQuery($query, $rule['rule']);
        }

        $query->unloadDocument();
        return $result;
    }

    protected function excuteQuery($eq, $rule)
    {
        if (empty($eq) || empty($rule)) {
            return null;
        }

        foreach ($rule as $key => $value) {
            if ($key == $value) {
                $eq = $eq->{$key}();
            } else {
                $eq = $eq->{$key}($value);
            }
        }
        if (array_key_exists('html',$rule)){
            $eq = Filter::htmlFilter($eq);
        }
        return $eq;
    }

    protected function replacePageKey($key, $replace, &$str)
    {
        if (is_string($str)) {
            $str = str_replace($key, $replace, $str);
        } else if (is_array($str)) {
            foreach ($str as $arrKey => &$arrValue) {
                $arrValue = str_replace($key, $replace, $arrValue);
            }
        }

    }

    /**
     * 提取数字
     * @param string $str
     * @return string
     */
    protected function findNum($str=''){
        $str=trim($str);
        if(empty($str)) return '';
        $pattern = "/\d+/";
        preg_match_all($pattern,$str,$matches);
        return !empty($matches[0]) ? $matches[0][0] : '';
    }
}